### ISSUE TITLE
Crash with Server Storage

### ISSUE THREAD

**Issue by sternschnaube** [tanchevk/stacksizedisplay#1]
https://modrinth.com/mod/server-storage

Fabric 1.21, latest Fabric Loader and Fabric API.
**Opened the terminal and got this crash:**

java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(Unknown Source)
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(Unknown Source)
	at knot//tanchevk.stacksizedisplay.StackSizeDisplay.itemStackTooltipHandler(StackSizeDisplay.kt:69)
	at knot//net.minecraft.class_1799.modifyReturnValue$lfh000$stacksizedisplay$onGetTooltip(class_1799.java:12113)
	at knot//net.minecraft.class_1799.method_7950(class_1799.java:746)
	at knot//net.minecraft.class_437.method_25408(class_437.java:243)
	at knot//net.minecraft.class_465.method_51454(class_465.java:187)
	at knot//net.minecraft.class_465.method_2380(class_465.java:182)
	at knot//net.minecraft.class_476.method_25394(class_476.java:28)
	at knot//net.minecraft.class_437.method_47413(class_437.java:117)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$313(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$fgp000$fabric-screen-api-v1$onRenderScreen(class_757.java:7586)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by tanchevk** [comment]
Server Storage changes tooltip handling for the item stacks in its terminal in a way that changes the `getTooltip` method parameter `tooltip` to an immutable list, which does not allow modifying the tooltip post-factum.
Unfortunately, this isn't easily fixable on my end, afaik. The best solution I can come up with is to not modify the tooltip if it's immutable

**Comment by tanchevk** [comment]
The hotfix for this will probably be released as release 1.0.1 once I finish testing it, which will probably happen sometime before the end of this week

**Comment by venaminecraft** [comment]
Thanks for the fix 😄
I can test the build if you want.

**Comment by tanchevk** [comment]
I have some minor things to fix and then I'll build a jar for testing, probably sometime today

**Comment by tanchevk** [comment]
I've assembled a testing build, which can be found [here](https://modrinth.com/mod/stacksizedisplay/version/1.0.1). It **should** fix issues with immutable tooltips. Hopefully.
